site_name: AIForged Documentation

theme:
  name: material
  features:
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: slate
      primary: teal
      accent: indigo
    - scheme: default
      primary: teal
      accent: indigo

plugins:
  - search
  
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight