site_name: AIForged Documentation

theme:
  name: material
  logo: assets/logo.png        # make sure this file exists
  favicon: assets/favicon.ico  # optional
  features:
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: slate
      primary: teal
      accent: indigo
    - scheme: default
      primary: teal
      accent: indigo

plugins:
  - search
  
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight

nav:
  - Home: index.md
  - Documents:
      - Overview: documents/index.md
  - Services:
      - Overview: services/index.md
  - Rules engine:
      - Overview: rules-engine/index.md
  - SDK:
      - Overview: sdk/index.md
  - UiPath activities:
      - Overview: uipath-activities/index.md
  - Projects:
      - Overview: projects/index.md
  - Service users:
      - Overview: service-users/index.md
  - Custom service code:
      - Overview: custom-service-code/index.md
  - Deprecated info:
      - Overview: depricated-info/index.md